### ISSUE TITLE
use on osx

### ISSUE THREAD

**Issue by atomotic** [egh/sparchive#2]
on osx i got the following error.
i suspect that is something related to zippath https://github.com/egh/sparchive/blob/master/sparchive/archive.py#L92
but i don't manage to catch the error

```
~ sparchive file data.csv

Failed to open -k: No such file or directory
Fatal error - exiting
Traceback (most recent call last):
  File "/usr/local/bin/sparchive", line 9, in <module>
    load_entry_point('sparchive==0.1.1', 'console_scripts', 'sparchive')()
  File "build/bdist.macosx-10.6-x86_64/egg/sparchive/cli.py", line 40, in main
  File "build/bdist.macosx-10.6-x86_64/egg/sparchive/filer.py", line 46, in file
  File "build/bdist.macosx-10.6-x86_64/egg/sparchive/archive.py", line 92, in add_version
  File "build/bdist.macosx-10.6-x86_64/egg/sparchive/rzip.py", line 24, in __exit__
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpF7vCfE'
```

**Comment by egh** [comment]
Unfortunately I don't have a mac os dev box. Could you install nose and run `nosetests` to get the test output? That might help me figure out what is happening here. Thanks so much for the bug report!

**Comment by atomotic** [comment]
```
➜  sparchive git:(master) ✗ nosetests
Failed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
E.Failed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
E.Failed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
E.Failed to open -k: No such file or directory
Fatal error - exiting
E.Failed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
EFailed to open -k: No such file or directory
Fatal error - exiting
EEEEFFailed to open tests/fixtures/foobar/foo: No such file or directory
Fatal error - exiting
E
======================================================================
ERROR: test_add_100_versions (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 86, in test_add_100_versions
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpXFivQ6'

======================================================================
ERROR: test_add_dir (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 93, in test_add_dir
    a.add_version([dir])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpuBfuep'

======================================================================
ERROR: test_add_file (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 65, in test_add_file
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmp4ZBqjm'

======================================================================
ERROR: test_add_unicode_file (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 73, in test_add_unicode_file
    a.add_version([i])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpD2njI3'

======================================================================
ERROR: test_external_attr (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 176, in test_external_attr
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpLyhp25'

======================================================================
ERROR: test_extract (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 105, in test_extract
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpiKtI9k'

======================================================================
ERROR: test_has_version (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 47, in test_has_version
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpbElnfd'

======================================================================
ERROR: test_has_version_dir (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 55, in test_has_version_dir
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpDArRyD'

======================================================================
ERROR: test_is_entries (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 186, in test_is_entries
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpfpyM6w'

======================================================================
ERROR: test_timestamps (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 163, in test_timestamps
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpNnpr8m'

======================================================================
ERROR: test_zip_versions (archive_test.TestArchive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/archive_test.py", line 36, in test_zip_versions
    a.add_version([foo])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmp_idCxT'

======================================================================
ERROR: test_cli (cli_test.CliTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/cli_test.py", line 29, in test_cli
    sparchive.cli.main(["addversion", a, foo])
  File "/private/tmp/sparchive/sparchive/cli.py", line 36, in main
    a.add_version(args.version_path)
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpa8AUa6'

======================================================================
ERROR: test_cli_addversion (cli_test.CliTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/cli_test.py", line 49, in test_cli_addversion
    sparchive.cli.main(['addversion', a, 'foo', 'bar'])
  File "/private/tmp/sparchive/sparchive/cli.py", line 36, in main
    a.add_version(args.version_path)
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpRa61n2'

======================================================================
ERROR: test_cli_extract (cli_test.CliTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/cli_test.py", line 56, in test_cli_extract
    sparchive.cli.main(["addversion", a, foo])
  File "/private/tmp/sparchive/sparchive/cli.py", line 36, in main
    a.add_version(args.version_path)
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmp7b7PAQ'

======================================================================
ERROR: test_cli_file (cli_test.CliTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/cli_test.py", line 43, in test_cli_file
    sparchive.cli.main(['file', '-r', archive, foo])
  File "/private/tmp/sparchive/sparchive/cli.py", line 40, in main
    result = filer.file(p)
  File "/private/tmp/sparchive/sparchive/filer.py", line 46, in file
    archive.add_version([path])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpFVjBnp'

======================================================================
ERROR: test_file (filer_test.FilerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/filer_test.py", line 38, in test_file
    results = filer.file('foobar')
  File "/private/tmp/sparchive/sparchive/filer.py", line 46, in file
    archive.add_version([path])
  File "/private/tmp/sparchive/sparchive/archive.py", line 92, in add_version
    rzip.compress(zippath, tmprzip)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 24, in __exit__
    os.unlink(self.uncomp_path)
OSError: [Errno 2] No such file or directory: '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpVbEjwc'

======================================================================
ERROR: test_find_archive_path (filer_test.FilerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/filer_test.py", line 14, in setUp
    os.utime(foo, (978307200,  978307200))
OSError: [Errno 2] No such file or directory: 'tests/fixtures/foobar/foo'

======================================================================
ERROR: test_find_file (filer_test.FilerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/filer_test.py", line 14, in setUp
    os.utime(foo, (978307200,  978307200))
OSError: [Errno 2] No such file or directory: 'tests/fixtures/foobar/foo'

======================================================================
ERROR: test_get_mtime (filer_test.FilerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/filer_test.py", line 14, in setUp
    os.utime(foo, (978307200,  978307200))
OSError: [Errno 2] No such file or directory: 'tests/fixtures/foobar/foo'

======================================================================
ERROR: test_uncompress_file (rzip_test.TestRzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/rzip_test.py", line 23, in test_uncompress_file
    rzip.compress(p, prz)
  File "/private/tmp/sparchive/sparchive/rzip.py", line 7, in compress
    subprocess.check_call(args)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['rzip', 'tests/fixtures/foobar/foo', '-k', '-6', '-o', '/var/folders/n2/kh7gqw416z53zjw7hh3478qh0000gn/T/tmpdy3mc9']' returned non-zero exit status 1

======================================================================
FAIL: test_compress_file (rzip_test.TestRzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sparchive/tests/rzip_test.py", line 12, in test_compress_file
    assert(os.path.exists(p))
AssertionError

----------------------------------------------------------------------
Ran 25 tests in 0.316s

FAILED (errors=20, failures=1)
```

**Comment by egh** [comment]
Thanks. I think I'm creating temp file names in a way that doesn't work on Mac OS X. I'll change the way I'm doing this.

**Comment by egh** [comment]
I just pushed up a change that might fix this. If you could test it out I'd appreciate it. Thanks!
